### ISSUE TITLE
Code can be improved by using Buffer instead of Array

### ISSUE THREAD

**Issue by timohanke** [aviate-labs/encoding.mo#1]
https://github.com/aviate-labs/encoding.mo/blob/18d464469f1abb3f5bacc61a8359a154c7340c39/src/Hex.mo#L106

Compiler warning:
```
field append is deprecated: Array.append has critical performance flaws; use a Buffer, and Buffer.append, instead.
```

**Comment by q-uint** [comment]
Hi @timohanke, thanks for reporting this! I must have missed that `append` when I went through all the packages.
