### ISSUE TITLE
Code could use base library

### ISSUE THREAD

**Issue by timohanke** [aviate-labs/encoding.mo#3]
https://github.com/aviate-labs/encoding.mo/blob/59c5caa398f62a882441159b1bb9c123cfb948c0/src/Hex.mo#L33-L48

Instead of implementing by hand, the code could use `Text.map(.., toLower)` in order to normalize each of the two string and then use `Text.equal` to compare two strings. 

See https://smartcontracts.org/docs/base-libraries/Text.html

**Comment by q-uint** [comment]
I did not do this because [`toLower`](https://github.com/dfinity/motoko-base/blob/be85b15dc9fb45b3f24d83fccd2b24c3d19bc57d/src/Char.mo#L23) is not exposed by the base library.

**Comment by timohanke** [comment]
But you have defined your own `toLower` and can use it here.

**Comment by q-uint** [comment]
> But you have defined your own toLower and can use it here.

Oh, yeah, it's been a while since I wrote the code. 😅

---

Thanks for opening the issue!
